items = [
	["beumi","beumi_falsch.mp3",0],
	["beuno","beuno_falsch.mp3",0],
	["beusa","beusa_falsch.mp3",0],
	["eufo","eufo_falsch.mp3",0],
	["euso","euso_falsch.mp3",0],
	["feuli","feuli_falsch.mp3",0],
	["feuma","feuma_falsch.mp3",0],
	["feuso","feuso_falsch.mp3",0],
	["geufu","geufu_falsch.mp3",0],
	["geume","geume_falsch.mp3",0],
	["geuso","geuso_falsch.mp3",0],
	["hexaf","hexaf_falsch.mp3",0],
	["hexim","hexim_falsch.mp3",0],
	["hexol","hexol_falsch.mp3",0],
	["jafi","jafi_falsch.mp3",0],
	["jale","jale_falsch.mp3",0],
	["jara","jara_falsch.mp3",0],
	["jeli","jeli_falsch.mp3",0],
	["jenu","jenu_falsch.mp3",0],
	["jera","jera_falsch.mp3",0],
	["neufu","neufu_falsch.mp3",0],
	["neumi","neumi_falsch.mp3",0],
	["pyme","pyme_falsch.mp3",0],
	["pyri","pyri_falsch.mp3",0],
	["quafu","quafu_falsch.mp3",0],
	["qualo","qualo_falsch.mp3",0],
	["quase","quase_falsch.mp3",0],
	["scheuli","scheuli_falsch.mp3",0],
	["scheuno","scheuno_falsch.mp3",0],
	["schoefo","schoefo_falsch.mp3",0],
	["schoela","schoela_falsch.mp3",0],
	["schoenu","schoenu_falsch.mp3",0],
	["schoese","schoese_falsch.mp3",0],
	["speife","speife_falsch.mp3",0],
	["speira","speira_falsch.mp3",0],
	["spelo","spelo_falsch.mp3",0],
	["speni","speni_falsch.mp3",0],
	["stafi","stafi_falsch.mp3",0],
	["stana","stana_falsch.mp3",0],
	["stasu","stasu_falsch.mp3",0],
	["steila","steila_falsch.mp3",0],
	["tyli","tyli_falsch.mp3",0],
	["vane","vane_falsch.mp3",0],
	["viru","viru_falsch.mp3",0],
	["vono","vono_falsch.mp3",0],
	["vufo","vufo_falsch.mp3",0],
	["xila","xila_falsch.mp3",0],
	["xime","xime_falsch.mp3",0],
	["xisu","xisu_falsch.mp3",0],
	["zale","zale_falsch.mp3",0],
	["zamo","zamo_falsch.mp3",0],
	["zasi","zasi_falsch.mp3",0],
	["zili","zili_falsch.mp3",0],
	["zisa","zisa_falsch.mp3",0],
	["beulu","beulu_richtig.mp3",1],
	["beure","beure_richtig.mp3",1],
	["euma","euma_richtig.mp3",1],
	["euni","euni_richtig.mp3",1],
	["eure","eure_richtig.mp3",1],
	["feufu","feufu_richtig.mp3",1],
	["feune","feune_richtig.mp3",1],
	["geula","geula_richtig.mp3",1],
	["geusi","geusi_richtig.mp3",1],
	["hexef","hexef_richtig.mp3",1],
	["hexun","hexun_richtig.mp3",1],
	["jamo","jamo_richtig.mp3",1],
	["jasu","jasu_richtig.mp3",1],
	["jemo","jemo_richtig.mp3",1],
	["jese","jese_richtig.mp3",1],
	["neulo","neulo_richtig.mp3",1],
	["neune","neune_richtig.mp3",1],
	["neusa","neusa_richtig.mp3",1],
	["pyfu","pyfu_richtig.mp3",1],
	["pyno","pyno_richtig.mp3",1],
	["pysa","pysa_richtig.mp3",1],
	["quani","quani_richtig.mp3",1],
	["quara","quara_richtig.mp3",1],
	["scheufu","scheufu_richtig.mp3",1],
	["scheura","scheura_richtig.mp3",1],
	["scheuse","scheuse_richtig.mp3",1],
	["schoeme","schoeme_richtig.mp3",1],
	["speilu","speilu_richtig.mp3",1],
	["speimi","speimi_richtig.mp3",1],
	["speino","speino_richtig.mp3",1],
	["spele","spele_richtig.mp3",1],
	["spema","spema_richtig.mp3",1],
	["spesu","spesu_richtig.mp3",1],
	["stalo","stalo_richtig.mp3",1],
	["stame","stame_richtig.mp3",1],
	["steifo","steifo_richtig.mp3",1],
	["steime","steime_richtig.mp3",1],
	["steiru","steiru_richtig.mp3",1],
	["steisi","steisi_richtig.mp3",1],
	["tyma","tyma_richtig.mp3",1],
	["tyne","tyne_richtig.mp3",1],
	["tyru","tyru_richtig.mp3",1],
	["tyso","tyso_richtig.mp3",1],
	["vala","vala_richtig.mp3",1],
	["vano","vano_richtig.mp3",1],
	["vari","vari_richtig.mp3",1],
	["vasu","vasu_richtig.mp3",1],
	["vifo","vifo_richtig.mp3",1],
	["vila","vila_richtig.mp3",1],
	["vimi","vimi_richtig.mp3",1],
	["vise","vise_richtig.mp3",1],
	["vofa","vofa_richtig.mp3",1],
	["volu","volu_richtig.mp3",1],
	["vomi","vomi_richtig.mp3",1],
	["vore","vore_richtig.mp3",1],
	["vume","vume_richtig.mp3",1],
	["vuni","vuni_richtig.mp3",1],
	["vura","vura_richtig.mp3",1],
	["vuru","vuru_richtig.mp3",1],
	["xilo","xilo_richtig.mp3",1],
	["xine","xine_richtig.mp3",1],
	["zafa","zafa_richtig.mp3",1],
	["zanu","zanu_richtig.mp3",1],
	["zefo","zefo_richtig.mp3",1],
	["zele","zele_richtig.mp3",1],
	["zema","zema_richtig.mp3",1],
	["zeni","zeni_richtig.mp3",1],
	["zeru","zeru_richtig.mp3",1],
	["zifu","zifu_richtig.mp3",1],
	["zile","zile_richtig.mp3",1],
	["zino","zino_richtig.mp3",1],
	["zufe","zufe_richtig.mp3",1],
	["zula","zula_richtig.mp3",1],
	["zumo","zumo_richtig.mp3",1],
	["zuri","zuri_richtig.mp3",1],
	["zusu","zusu_richtig.mp3",1]
]


rater = Test.create(name: "Rater", info: "", type_info:"", shorthand: "RTR", len: items.size, time: 60, subject: "Deutsch", construct: "Rater", student_access:false, level: "N1", archive: false)

it = rater.items.build(itemtext: "Hallo", difficulty: 0, itemtype:-1, itemview:"items/userbased/preparationUser")
it.save

i=0
while i<items.size do
  it = rater.items.build(itemtext: items[i][0], mediapath:{"audios"=>["/audio/rater/3a/marie/" + items[i][1]]}, difficulty: items[i][2], itemtype:0, itemview:"items/userbased/raterItem")
  it.save
  i= i+1
end

it = rater.items.build(itemtext: "Ende", difficulty: 0, itemtype:1, itemview:"items/userbased/raterEnd")
it.save
rater.save





