items = [
	["euma.mp3",0],
	["euni.mp3",0],
	["geufu.mp3",0],
	["jera.mp3",0],
	["pyno.mp3",0],
	["scheuli.mp3",0],
	["schöme.mp3",0],
	["schöse.mp3",0],
	["speino.mp3",0],
	["vano.mp3",0],
	["vifo.mp3",0],
	["vimi.mp3",0],
	["vofa.mp3",0],
	["zasi.mp3",0],
	["zeni.mp3",0],
	["zumo.mp3",0],
	["beulu.mp3",1],
	["beumi.mp3",1],
	["beuno.mp3",1],
	["beure.mp3",1],
	["beusa.mp3",1],
	["eufo.mp3",1],
	["eure.mp3",1],
	["eusu.mp3",1],
	["feufu.mp3",1],
	["feuli.mp3",1],
	["feuma.mp3",1],
	["feune.mp3",1],
	["feuso.mp3",1],
	["geula.mp3",1],
	["geume.mp3",1],
	["geusi.mp3",1],
	["geuso.mp3",1],
	["hexaf.mp3",1],
	["hexef.mp3",1],
	["hexim.mp3",1],
	["hexol.mp3",1],
	["hexun.mp3",1],
	["jafi.mp3",1],
	["jale.mp3",1],
	["jamo.mp3",1],
	["jara.mp3",1],
	["jasu.mp3",1],
	["jeli.mp3",1],
	["jemo.mp3",1],
	["jenu.mp3",1],
	["jese.mp3",1],
	["neufu.mp3",1],
	["neulo.mp3",1],
	["neumi.mp3",1],
	["neune.mp3",1],
	["neusa.mp3",1],
	["pyfu.mp3",1],
	["pyme.mp3",1],
	["pyri.mp3",1],
	["pysa.mp3",1],
	["quafu.mp3",1],
	["qualo.mp3",1],
	["quani.mp3",1],
	["quara.mp3",1],
	["quase.mp3",1],
	["scheufu.mp3",1],
	["scheuno.mp3",1],
	["scheura.mp3",1],
	["scheuse.mp3",1],
	["schöfo.mp3",1],
	["schöla.mp3",1],
	["schöme.mp3",1],
	["schönu.mp3",1],
	["speife.mp3",1],
	["speilu.mp3",1],
	["speimi.mp3",1],
	["speira.mp3",1],
	["spele.mp3",1],
	["spelo.mp3",1],
	["spema.mp3",1],
	["speni.mp3",1],
	["spesu.mp3",1],
	["stafi.mp3",1],
	["stalo.mp3",1],
	["stame.mp3",1],
	["stana.mp3",1],
	["stasu.mp3",1],
	["steifo.mp3",1],
	["steila.mp3",1],
	["steime.mp3",1],
	["steiru.mp3",1],
	["steisi.mp3",1],
	["tyli.mp3",1],
	["tyma.mp3",1],
	["tyne.mp3",1],
	["tyru.mp3",1],
	["tysio.mp3",1],
	["vala.mp3",1],
	["vane.mp3",1],
	["vari.mp3",1],
	["vasu.mp3",1],
	["vila.mp3",1],
	["viru.mp3",1],
	["vise.mp3",1],
	["volu.mp3",1],
	["vomi.mp3",1],
	["vono.mp3",1],
	["vore.mp3",1],
	["vufo.mp3",1],
	["vume.mp3",1],
	["vuni.mp3",1],
	["vura.mp3",1],
	["vuru.mp3",1],
	["xila.mp3",1],
	["xilo.mp3",1],
	["xime.mp3",1],
	["xine.mp3",1],
	["xisu.mp3",1],
	["zafa.mp3",1],
	["zale.mp3",1],
	["zamo.mp3",1],
	["zanu.mp3",1],
	["zefo.mp3",1],
	["zele.mp3",1],
	["zema.mp3",1],
	["zeru.mp3",1],
	["zifu.mp3",1],
	["zile.mp3",1],
	["zili.mp3",1],
	["zino.mp3",1],
	["zisa.mp3",1],
	["zufe.mp3",1],
	["zula.mp3",1],
	["zuri.mp3",1],
	["zusu.mp3",1]
]

rater = TestRater.create(name: "Pseudowörter lesen", info: "", type_info:"", shorthand: "RTR", len: items.size + 2, 
	time: 60, subject: "Lehrkraftübungen", construct: "Leseflüssigkeit", student_access:false, level: "N 3a_1", archive: false, :generic_views => {'student' => 'rater/student_overview.html.erb', 
			'assessment' => 'rater/assessment_overview.html.erb'})

it = rater.items.build(itemtext: "Hallo", difficulty: 0, itemtype:-1, itemview:"items/userbased/preparationUser")
it.save

i=0
while i<items.size do
	if items[i][1] == 0
  		it = rater.items.build(itemtext: items[i][0].split('.')[0], mediapath:{"audios"=>["/audio/rater/3a_Marie/falsch/" + items[i][0]]}, difficulty: items[i][1], 
  					itemtype:0, itemview:"items/userbased/raterItem")
  		it.save
  	else
  		it = rater.items.build(itemtext: items[i][0].split('.')[0], mediapath:{"audios"=>["/audio/rater/3a_Marie/richtig/" + items[i][0]]}, difficulty: items[i][1], 
  					itemtype:0, itemview:"items/userbased/raterItem")
  		it.save
  	end
  i= i+1
end

it = rater.items.build(itemtext: "Ende", difficulty: 0, itemtype:1, itemview:"items/userbased/raterEnd")
it.save
rater.save


items = [
	["beumi.mp3",0],
	["beuno.mp3",0],
	["beusa.mp3",0],
	["eufo.mp3",0],
	["eusu.mp3",0],
	["feuli.mp3",0],
	["feuma.mp3",0],
	["feuso.mp3",0],
	["geufu.mp3",0],
	["geume.mp3",0],
	["geuso.mp3",0],
	["hexaf.mp3",0],
	["hexim.mp3",0],
	["hexol.mp3",0],
	["jafi.mp3",0],
	["jale.mp3",0],
	["jara.mp3",0],
	["jeli.mp3",0],
	["jenu.mp3",0],
	["jera.mp3",0],
	["neufu.mp3",0],
	["neumi.mp3",0],
	["pyme.mp3",0],
	["pyri.mp3",0],
	["quafu.mp3",0],
	["qualo.mp3",0],
	["quase.mp3",0],
	["scheuli.mp3",0],
	["scheuno.mp3",0],
	["schöfo.mp3",0],
	["schöla.mp3",0],
	["schönu.mp3",0],
	["schöse.mp3",0],
	["speife.mp3",0],
	["speira.mp3",0],
	["spelo.mp3",0],
	["speni.mp3",0],
	["stafi.mp3",0],
	["stana.mp3",0],
	["stasu.mp3",0],
	["steila.mp3",0],
	["tyli.mp3",0],
	["vane.mp3",0],
	["viru.mp3",0],
	["vono.mp3",0],
	["vufo.mp3",0],
	["xila.mp3",0],
	["xime.mp3",0],
	["xisu.mp3",0],
	["zale.mp3",0],
	["zamo.mp3",0],
	["zasi.mp3",0],
	["zili.mp3",0],
	["zisa.mp3",0],
	["beulu.mp3",1],
	["beure.mp3",1],
	["euma.mp3",1],
	["euni.mp3",1],
	["eure.mp3",1],
	["feufu.mp3",1],
	["feune.mp3",1],
	["geula.mp3",1],
	["geusi.mp3",1],
	["hexef.mp3",1],
	["hexun.mp3",1],
	["jamo.mp3",1],
	["jasu.mp3",1],
	["jemo.mp3",1],
	["jese.mp3",1],
	["neulo.mp3",1],
	["neune.mp3",1],
	["neusa.mp3",1],
	["pyfu.mp3",1],
	["pyno.mp3",1],
	["pysa.mp3",1],
	["quani.mp3",1],
	["quara.mp3",1],
	["scheufu.mp3",1],
	["scheura.mp3",1],
	["scheuse.mp3",1],
	["schöme.mp3",1],
	["speilu.mp3",1],
	["speimi.mp3",1],
	["speino.mp3",1],
	["spele.mp3",1],
	["spema.mp3",1],
	["spesu.mp3",1],
	["stalo.mp3",1],
	["stame.mp3",1],
	["steifo.mp3",1],
	["steime.mp3",1],
	["steiru.mp3",1],
	["steisi.mp3",1],
	["tyma.mp3",1],
	["tyne.mp3",1],
	["tyru.mp3",1],
	["tyso.mp3",1],
	["vala.mp3",1],
	["vano.mp3",1],
	["vari.mp3",1],
	["vasu.mp3",1],
	["vifo.mp3",1],
	["vila.mp3",1],
	["vimi.mp3",1],
	["vise.mp3",1],
	["vofa.mp3",1],
	["volu.mp3",1],
	["vomi.mp3",1],
	["vore.mp3",1],
	["vume.mp3",1],
	["vuni.mp3",1],
	["vura.mp3",1],
	["vuru.mp3",1],
	["xilo.mp3",1],
	["xine.mp3",1],
	["zafa.mp3",1],
	["zanu.mp3",1],
	["zefo.mp3",1],
	["zele.mp3",1],
	["zema.mp3",1],
	["zeni.mp3",1],
	["zeru.mp3",1],
	["zifu.mp3",1],
	["zile.mp3",1],
	["zino.mp3",1],
	["zufe.mp3",1],
	["zula.mp3",1],
	["zumo.mp3",1],
	["zuri.mp3",1],
	["zusu.mp3",1]
]

rater = TestRater.create(name: "Pseudowörter lesen", info: "", type_info:"", shorthand: "RTR", len: items.size + 2, 
	time: 60, subject: "Lehrkraftübungen", construct: "Leseflüssigkeit", student_access:false, level: "N 3a_2", archive: false, :generic_views => {'student' => 'rater/student_overview.html.erb',
		'assessment' => 'rater/assessment_overview.html.erb'})

it = rater.items.build(itemtext: "Hallo", difficulty: 0, itemtype:-1, itemview:"items/userbased/preparationUser")
it.save

i=0
while i<items.size do
	if items[i][1] == 0
  		it = rater.items.build(itemtext: items[i][0].split('.')[0], mediapath:{"audios"=>["/audio/rater/3a_Rebecca/falsch/" + items[i][0]]}, difficulty: items[i][1], 
  					itemtype:0, itemview:"items/userbased/raterItem")
  		it.save
  	else
  		it = rater.items.build(itemtext: items[i][0].split('.')[0], mediapath:{"audios"=>["/audio/rater/3a_Rebecca/richtig/" + items[i][0]]}, difficulty: items[i][1], 
  					itemtype:0, itemview:"items/userbased/raterItem")
  		it.save
  	end
  i= i+1
end

it = rater.items.build(itemtext: "Ende", difficulty: 0, itemtype:1, itemview:"items/userbased/raterEnd")
it.save
rater.save


items = [
	["jäzi.mp3",0],
	["jeste.mp3",0],
	["quaspi.mp3",0],
	["quastä.mp3",0],
	["schäqui.mp3",0],
	["scheuße.mp3",0],
	["scheußer.mp3",0],
	["speju.mp3",0],
	["spixi.mp3",0],
	["stespi.mp3",0],
	["steße.mp3",0],
	["stezü.mp3",0],
	["stövo.mp3",0],
	["stuspu.mp3",0],
	["vaschä.mp3",0],
	["veißer.mp3",0],
	["zausta.mp3",0],
	["zeuzau.mp3",0],
	["züßer.mp3",0],
	["züstu.mp3",0],
	["zuzau.mp3",0],
	["hexpy.mp3",1],
	["hexqui.mp3",1],
	["hexsteu.mp3",1],
	["hexze.mp3",1],
	["hexzü.mp3",1],
	["jästau.mp3",1],
	["jastu.mp3",1],
	["jaty.mp3",1],
	["jaujä.mp3",1],
	["jauspi.mp3",1],
	["jäzeu.mp3",1],
	["jeußen.mp3",1],
	["jopy.mp3",1],
	["juqua.mp3",1],
	["juspeu.mp3",1],
	["juspi.mp3",1],
	["juße.mp3",1],
	["juzeu.mp3",1],
	["pyhex.mp3",1],
	["pyschu.mp3",1],
	["pysta.mp3",1],
	["quaja.mp3",1],
	["quäjau.mp3",1],
	["quajo.mp3",1],
	["quäjo.mp3",1],
	["quäschü.mp3",1],
	["quäspu.mp3",1],
	["quäva.mp3",1],
	["quavi.mp3",1],
	["quipy.mp3",1],
	["quispi.mp3",1],
	["schäßer.mp3",1],
	["schävei.mp3",1],
	["schäzä.mp3",1],
	["schäzeu.mp3",1],
	["scheujä.mp3",1],
	["scheuvei.mp3",1],
	["schöjä.mp3",1],
	["schüstö.mp3",1],
	["schüty.mp3",1],
	["schüvi.mp3",1],
	["spähex.mp3",1],
	["spajo.mp3",1],
	["späjo.mp3",1],
	["spapy.mp3",1],
	["späschü.mp3",1],
	["späspeu.mp3",1],
	["spävei.mp3",1],
	["späzö.mp3",1],
	["speistu.mp3",1],
	["speiva.mp3",1],
	["speivi.mp3",1],
	["speize.mp3",1],
	["spety.mp3",1],
	["speuspi.mp3",1],
	["spijo.mp3",1],
	["spiste.mp3",1],
	["spity.mp3",1],
	["spiva.mp3",1],
	["spujeu.mp3",1],
	["spüspä.mp3",1],
	["spuße.mp3",1],
	["spusta.mp3",1],
	["spüsto.mp3",1],
	["spüva.mp3",1],
	["spüvi.mp3",1],
	["staquä.mp3",1],
	["stäschü.mp3",1],
	["stästö.mp3",1],
	["staustei.mp3",1],
	["stazau.mp3",1],
	["stazü.mp3",1],
	["steiqua.mp3",1],
	["steischeu.mp3",1],
	["steisteu.mp3",1],
	["steity.mp3",1],
	["steizau.mp3",1],
	["stespe.mp3",1],
	["steuschö.mp3",1],
	["steuspeu.mp3",1],
	["steuvi.mp3",1],
	["steuvo.mp3",1],
	["steuza.mp3",1],
	["steva.mp3",1],
	["stezeu.mp3",1],
	["stije.mp3",1],
	["stispü.mp3",1],
	["stiste.mp3",1],
	["stisto.mp3",1],
	["stöhex.mp3",1],
	["stoje.mp3",1],
	["stoxi.mp3",1],
	["stözi.mp3",1],
	["stözö.mp3",1],
	["stuqua.mp3",1],
	["stuste.mp3",1],
	["stuva.mp3",1],
	["stuvo.mp3",1],
	["stzeizü.mp3",1],
	["tyqui.mp3",1],
	["tyspa.mp3",1],
	["tystau.mp3",1],
	["vaßer.mp3",1],
	["veihex.mp3",1],
	["veiquä.mp3",1],
	["veischeu.mp3",1],
	["veizei.mp3",1],
	["veizio.mp3",1],
	["vistu.mp3",1],
	["vöja.mp3",1],
	["voqua.mp3",1],
	["vöstau.mp3",1],
	["vovei.mp3",1],
	["vözeu.mp3",1],
	["vypi.mp3",1],
	["xischa.mp3",1],
	["xispeu.mp3",1],
	["xizä.mp3",1],
	["xysti.mp3",1],
	["zäpy.mp3",1],
	["zaqua.mp3",1],
	["zäschü.mp3",1],
	["zäßen.mp3",1],
	["zästä.mp3",1],
	["zastau.mp3",1],
	["zasto.mp3",1],
	["zauja.mp3",1],
	["zausto.mp3",1],
	["zauza.mp3",1],
	["zauzä.mp3",1],
	["zauzü.mp3",1],
	["zavio.mp3",1],
	["zeißen.mp3",1],
	["zeistau.mp3",1],
	["zespü.mp3",1],
	["zesta.mp3",1],
	["zestau.mp3",1],
	["zeujau.mp3",1],
	["zeuqua.mp3",1],
	["zeustö.mp3",1],
	["zeuzö.mp3",1],
	["zevö.mp3",1],
	["zeza.mp3",1],
	["zista.mp3",1],
	["zivei.mp3",1],
	["zöästa.mp3",1],
	["zöqua.mp3",1],
	["zösti.mp3",1],
	["zövi.mp3",1],
	["zözi.mp3",1],
	["zujau.mp3",1],
	["züjau.mp3",1],
	["züjeu.mp3",1],
	["zuschu.mp3",1],
	["zuspei.mp3",1],
	["zußen.mp3",1],
	["zustau.mp3",1],
	["züvö.mp3",1]
]

rater = TestRater.create(name: "Pseudowörter lesen", info: "", type_info:"", shorthand: "RTR", len: items.size + 2, 
	time: 60, subject: "Lehrkraftübungen", construct: "Leseflüssigkeit", student_access:false, level: "N 3b_1", archive: false, :generic_views => {'student' => 'rater/student_overview.html.erb',
			'assessment' => 'rater/assessment_overview.html.erb'})

it = rater.items.build(itemtext: "Hallo", difficulty: 0, itemtype:-1, itemview:"items/userbased/preparationUser")
it.save

i=0
while i<items.size do
	if items[i][1] == 0
  		it = rater.items.build(itemtext: items[i][0].split('.')[0], mediapath:{"audios"=>["/audio/rater/3b_Marie/falsch/" + items[i][0]]}, difficulty: items[i][1], 
  					itemtype:0, itemview:"items/userbased/raterItem")
  		it.save
  	else
  		it = rater.items.build(itemtext: items[i][0].split('.')[0], mediapath:{"audios"=>["/audio/rater/3b_Marie/richtig/" + items[i][0]]}, difficulty: items[i][1], 
  					itemtype:0, itemview:"items/userbased/raterItem")
  		it.save
  	end
  i= i+1
end

it = rater.items.build(itemtext: "Ende", difficulty: 0, itemtype:1, itemview:"items/userbased/raterEnd")
it.save
rater.save


items = [
	["hexsteu.mp3",0],
	["hexze.mp3",0],
	["jauspi.mp3",0],
	["jeste.mp3",0],
	["juqua.mp3",0],
	["juspeu.mp3",0],
	["juzeu.mp3",0],
	["pyhex.mp3",0],
	["quajo.mp3",0],
	["quäjo.mp3",0],
	["quäva.mp3",0],
	["quipy.mp3",0],
	["quispi.mp3",0],
	["schäqui.mp3",0],
	["schöjä.mp3",0],
	["späspeu.mp3",0],
	["speivi.mp3",0],
	["spestö.mp3",0],
	["speuspi.mp3",0],
	["spixi.mp3",0],
	["spujeu.mp3",0],
	["spüspü.mp3",0],
	["spuße.mp3",0],
	["stastö.mp3",0],
	["staustei.mp3",0],
	["stazü.mp3",0],
	["steischeu.mp3",0],
	["steizau.mp3",0],
	["stespe.mp3",0],
	["steuschö.mp3",0],
	["steuspeu.mp3",0],
	["stispü.mp3",0],
	["stisto.mp3",0],
	["stoje.mp3",0],
	["stoxi.mp3",0],
	["stuqua.mp3",0],
	["stuspu.mp3",0],
	["tyqui.mp3",0],
	["vaschä.mp3",0],
	["vaßer.mp3",0],
	["veiquä.mp3",0],
	["veischeu.mp3",0],
	["vipy.mp3",0],
	["voquä.mp3",0],
	["vövei.mp3",0],
	["xischä.mp3",0],
	["zäpy.mp3",0],
	["zästä.mp3",0],
	["zeißen.mp3",0],
	["zeistau.mp3",0],
	["zespü.mp3",0],
	["zeujau.mp3",0],
	["zevö.mp3",0],
	["züjau.mp3",0],
	["zuspei.mp3",0],
	["zustu.mp3",0],
	["hexpy.mp3",1],
	["hexqui.mp3",1],
	["hexzü.mp3",1],
	["jästau.mp3",1],
	["jastu.mp3",1],
	["jaty.mp3",1],
	["jaujä.mp3",1],
	["jäzeu.mp3",1],
	["jäzi.mp3",1],
	["jeußen.mp3",1],
	["jopy.mp3",1],
	["juspi.mp3",1],
	["juße.mp3",1],
	["pyschü.mp3",1],
	["pysta.mp3",1],
	["quaja.mp3",1],
	["quäjau.mp3",1],
	["quäschü.mp3",1],
	["quaspi.mp3",1],
	["quäspu.mp3",1],
	["quastä.mp3",1],
	["quavi.mp3",1],
	["schäßer.mp3",1],
	["schävei.mp3",1],
	["schäzä.mp3",1],
	["schäzeu.mp3",1],
	["scheujä.mp3",1],
	["scheuße.mp3",1],
	["scheußer.mp3",1],
	["scheuvei.mp3",1],
	["schüstö.mp3",1],
	["schüty.mp3",1],
	["schüvi.mp3",1],
	["spähex.mp3",1],
	["späjo.mp3",1],
	["spapy.mp3",1],
	["späschü.mp3",1],
	["spävei.mp3",1],
	["späzö.mp3",1],
	["speistu.mp3",1],
	["speiva.mp3",1],
	["speize.mp3",1],
	["speju.mp3",1],
	["spety.mp3",1],
	["spijo.mp3",1],
	["spiste.mp3",1],
	["spity.mp3",1],
	["spiva.mp3",1],
	["spusta.mp3",1],
	["spüsto.mp3",1],
	["spüva.mp3",1],
	["spüvi.mp3",1],
	["staquä.mp3",1],
	["stäschü.mp3",1],
	["stästö.mp3",1],
	["stazau.mp3",1],
	["steiqua.mp3",1],
	["steisteu.mp3",1],
	["steity.mp3",1],
	["steizü.mp3",1],
	["stespi.mp3",1],
	["steße.mp3",1],
	["steuvi.mp3",1],
	["steuvo.mp3",1],
	["steuza.mp3",1],
	["steva.mp3",1],
	["stezeu.mp3",1],
	["stezü.mp3",1],
	["stije.mp3",1],
	["stiste.mp3",1],
	["stöhex.mp3",1],
	["stövo.mp3",1],
	["stözi.mp3",1],
	["stözö.mp3",1],
	["stuste.mp3",1],
	["stuva.mp3",1],
	["stuvo.mp3",1],
	["tyspa.mp3",1],
	["tystau.mp3",1],
	["veihex.mp3",1],
	["veißer.mp3",1],
	["veizei.mp3",1],
	["veizi.mp3",1],
	["vistu.mp3",1],
	["vöjä.mp3",1],
	["vostau.mp3",1],
	["vözeu.mp3",1],
	["xispeu.mp3",1],
	["xisti.mp3",1],
	["xizä.mp3",1],
	["zaqua.mp3",1],
	["zäschü.mp3",1],
	["zäßen.mp3",1],
	["zastau.mp3",1],
	["zasto.mp3",1],
	["zauja.mp3",1],
	["zausta.mp3",1],
	["zausto.mp3",1],
	["zauza.mp3",1],
	["zauzä.mp3",1],
	["zauzü.mp3",1],
	["zavi.mp3",1],
	["zesta.mp3",1],
	["zestau.mp3",1],
	["zeuqua.mp3",1],
	["zeustö.mp3",1],
	["zeuzau.mp3",1],
	["zeuzö.mp3",1],
	["zeza.mp3",1],
	["zista.mp3",1],
	["zivei.mp3",1],
	["zöqua.mp3",1],
	["zöstä.mp3",1],
	["zösti.mp3",1],
	["zövi.mp3",1],
	["zözi.mp3",1],
	["zujau.mp3",1],
	["züjeu.mp3",1],
	["zußen.mp3",1],
	["züßer.mp3",1],
	["zustau.mp3",1],
	["züstu.mp3",1],
	["züvö.mp3",1],
	["zuzau.mp3",1]
]

rater = TestRater.create(name: "Pseudowörter lesen", info: "", type_info:"", shorthand: "RTR", len: items.size + 2, 
	time: 60, subject: "Lehrkraftübungen", construct: "Leseflüssigkeit", student_access:false, level: "N 3b_2", archive: false, :generic_views => {'student' => 'rater/student_overview.html.erb',
				'assessment' => 'rater/assessment_overview.html.erb'})

it = rater.items.build(itemtext: "Hallo", difficulty: 0, itemtype:-1, itemview:"items/userbased/preparationUser")
it.save

i=0
while i<items.size do
	if items[i][1] == 0
  		it = rater.items.build(itemtext: items[i][0].split('.')[0], mediapath:{"audios"=>["/audio/rater/3b_Rebecca/falsch/" + items[i][0]]}, difficulty: items[i][1], 
  					itemtype:0, itemview:"items/userbased/raterItem")
  		it.save
  	else
  		it = rater.items.build(itemtext: items[i][0].split('.')[0], mediapath:{"audios"=>["/audio/rater/3b_Rebecca/richtig/" + items[i][0]]}, difficulty: items[i][1], 
  					itemtype:0, itemview:"items/userbased/raterItem")
  		it.save
  	end
  i= i+1
end

it = rater.items.build(itemtext: "Ende", difficulty: 0, itemtype:1, itemview:"items/userbased/raterEnd")
it.save
rater.save